### ISSUE TITLE
Can't import component

### ISSUE THREAD

**Issue by ooker777** [CarcajadaArtificial/lunchbox#3]
My `index.tsx`:
```tsx
import { Button } from 'lunchbox';
export default function Home() {
    return
        <Button>Click Me!</Button>;
}
```
The button just has the default appearance, not from the library. Manually copying the button component, src and deps from the lunchbox repo and changing the import to `import Button from "../components/Button/index.tsx";` doesn't work as well. 

Running the sample site work nevertheless. Do you know what's wrong?

**Comment by CarcajadaArtificial** [comment]
Hey! Honestly you're the first developer to use Lunchbox (thank you very much), and I wasn't expecting users so soon haha. For the appearance add the Stylesheet component to your `_app.tsx` file like so:

```tsx
import { Stylesheet } from 'lunchbox';
import type { State } from '@/plugins/session.ts';
import { defineApp } from '$fresh/server.ts';
import { Head } from '$fresh/runtime.ts';

export default defineApp<State>((_, ctx) => {
  return (
    <>
      <Head>
        <title>remember.land</title>
        <Stylesheet />
      </Head>
      <body class='clr-bg-panel clr-txt-base txt-paragraph'>
        <ctx.Component />
      </body>
    </>
  );
});
```

This, of course, is just temporal. Soon, Lunchbox will become a native Fresh plugin that will import styles automatically.

**Comment by ooker777** [comment]
Well, your first commit was in July 23, it has been more than half of a year. I guess it's still slow for the community to have a native UI framework?

**Comment by CarcajadaArtificial** [comment]
@ooker777 Yeah, I've been working on and off on this component library. I guess I made it look "too official", I'll add a warning sign that the project is still incomplete and will have breaking changes soon. And regarding the Lunchbox community, it was only me until now that you tried using it. Honestly, I didn't think anyone would see this project without me promoting it first.

**Comment by ooker777** [comment]
why don't you promote it? I just pick the first result I found in Google for UI library that is native to Fresh
